Allows to require/install an arbitrary version of pandoc

diff --git a/scripts/install_pandoc b/scripts/install_pandoc
--- a/scripts/install_pandoc
+++ b/scripts/install_pandoc
@@ -12,23 +12,32 @@ tools=""
 tools="$tools wget" # for getting a recent version of pandoc
 _check_tools $tools
 
-# install pandoc if the latest version is not in PATH
-pandoc_ver_inst=`which pandoc > /dev/null 2>&1 && pandoc -v | head -n 1 | sed -e 's/.* //' || echo "NONE"`
-pandoc_ver_latest=`wget -O - --max-redirect 0 https://github.com/jgm/pandoc/releases/latest 2>&1 | grep "Location:" | sed 's/.*\/tag\/\([^ "]*\).*/\1/'`
-if [ "$pandoc_ver_inst" = "$pandoc_ver_latest" ]
+# parameters
+args="$@"
+pandoc_ver_required="${PANDOC_VERSION:-}"
+
+if [ "${PANDOC_VERSION:-}" = "" ]
 then
-	echo "'pandoc' latest version ($pandoc_ver_latest) is already installed."
+	pandoc_ver_latest=`wget -O - --max-redirect 0 https://github.com/jgm/pandoc/releases/latest 2>&1 | grep "Location:" | sed 's/.*\/tag\/\([^ "]*\).*/\1/'`
+	pandoc_ver_required="$pandoc_ver_latest"
+fi
+
+# install pandoc if the latest version is not in PATH
+pandoc_ver_installed=`which pandoc > /dev/null 2>&1 && pandoc -v | head -n 1 | sed -e 's/.* //' || echo "NONE"`
+if [ "$pandoc_ver_installed" = "$pandoc_ver_required" ]
+then
+	echo "'pandoc' required version ($pandoc_ver_required) is already installed."
 else
-	echo "Installing pandoc $pandoc_ver_latest ..."
+	echo "Installing pandoc $pandoc_ver_required ..."
 	if `_is_deb`
 	then
-		pandoc_deb="pandoc-${pandoc_ver_latest}-1-amd64.deb"
-		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_latest/$pandoc_deb"
+		pandoc_deb="pandoc-${pandoc_ver_required}-1-amd64.deb"
+		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_required/$pandoc_deb"
 		dpkg -i "$pandoc_deb"
 		rm "$pandoc_deb"
 	else
-		pandoc_tgz="pandoc-${pandoc_ver_latest}-linux.tar.gz"
-		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_latest/$pandoc_tgz"
+		pandoc_tgz="pandoc-${pandoc_ver_required}-linux.tar.gz"
+		wget --quiet "https://github.com/jgm/pandoc/releases/download/$pandoc_ver_required/$pandoc_tgz"
 		install_root=/usr/local
 		#install_root=$HOME/.local
 		tar xvzf "$pandoc_tgz" --strip-components 1 -C "$install_root"
